
export const datasach = [
    {
        name: " Những Tù Nhân  của địa lý ",
        address: "tu",
        c: "best seller",
        id: 4,
        Click : 0,
        author: "Tim Marshall",
        intro: "Tác giả cho rằng yếu tố địa lý quyết định chính sách chính trị của các quốc gia. Những dãy núi, con sông, bình nguyên, sa mạc chính là những biên cương hữu hình khiến chính sách chính trị của nhiều lãnh đạo bị giới hạn. Từ đó, họ trở thành những tù nhân của địa lý.",
        Time: "2017",
        NXb: "Nha Nam",
    },
    {
        name: " Mùi Hương ",
        address: 2,
        l: "like",
        c: "best seller",
        id: 1 ,
        Click : 0,
    },
    {
        name: " Sức mạnh của người mẹ nhật ",
        address: 3,
        c: "best seller",
        id: 5 ,
        Click : 0,
    },
    {
        name: " Phía tây không có gì lạ ",
        address: 4,
        id: 1 ,
        Click : 0,
    },
    {
        name: " Nhà Giả Kim ",
        address: 5,
        c: "best seller",
        id: 5,
        Click : 0,
    },    {
        name: " Cha giàu cha nghèo ",
        address: 6,
        c: "best seller",
        Click : 0,
        id : 5,
    },
    {
        name: " Onepiece ",
        address: 7,
        c: "best seller",
        Click : 0 ,
        id : 7,
    },
    {
        name: " Bí Kí Kinh Doanh Của Người Do Thái  ",
        address: 8,
        Click : 0,
        id : 2,
    },
     {
        name: " Gió thổi mùa trăng năm ấy ",
        address:9,
        id : 1,
        Click : 0 ,
    }, 
    {
        name: " Đọc Vị Bất Kỳ Ai ",
        address:10,
        l: "like",
        id : 5,
        Click : 0,
    }, 
    {
        name: " Khéo Ăn khéo Nói Sẽ Được Lòng Thiên Hạ ",
        address: 11,
        l: "like",
        Click : 0,
        id : 5,
    }, 
    {
        name: " Nghệ Thuật Từ Chối ",
        address: 12,
        id : 6,
        Click : 0,
    },
    {
        name: " 21 Bài học cho thế kỷ 21 ",
        address: 13,
        id : 3,
        Click : 0,
        m: "moi",
    },    
    {
        name: " Lược Sử Tôn Giáo ",
        address:14,
        id : 4,
        Click : 0,
        m: "moi",
    },    
    {
        name: " Toán Học Một Chương Tiểu Thuyết ",
        address: 15,
        c: "best seller",
        id : 4,
        Click : 0,
    },  
    {
        name: " Lược Sử Chiến Tranh",
        address: 16,
        id : 3,
        Click : 0,
        intro:""
    },
    {
        name: " Phía Sau Cuộc Chiến  ",
        address: 17,
        c: "best seller",
        l: "like",
        id : 3,
        Click : 0,
    },
    {
        name: " Truyền Kì Mạn Lục ",
        address: 18,
        l: "like",
        id : 0,
        Click : 0,
    }, 
        {
        name: " Tắt Đèn ",
        address: 19,
        id : 0,
        Click : 0,
    }, 
    {
        name: " Nhật Kí Đặng Thùy Trâm ",
        address: 20,
        id : 0,
        Click : 0,
    }, 
    {
        name: " Lặng Yên Cho Nước Chảy",
        address:21,
        id : 0,
        Click : 0,
    }, 
    {
        name: " Ngoại ô ",
        address: 22,
        id : 0,
        Click : 0,
    }, 
    {
        name: " Chúc Mẹ ngủ Ngon ",
        address: 23,
        id : 1,
        Click : 0,
        m: "moi",
    }, 
    {
        name: " Donquixote ",
        address: 24,
        c: "best seller",
        l: "like",
        id : 1,
        Click : 0,
        m: "moi",
    },
    {
        name: " Bản Chất Của Người ",
        address: 25,
        l: "like",
        id : 1,
        Click : 0,
    },  
    {
        name: " Những Kẻ Bày Mưu ",
        address: 26,
        c: "best seller",
        l: "like",
        id : 1,
        Click : 0,
    },
    {
        name: " Tiệm Bánh Ngọt Lúc Nửa Đêm ",
        address: 27,
        c: "best seller",
        l: "like",
        id : 1,
        Click : 0,
        m:"moi",
    },
    {
        name: " Hoa Hồng Sa Mạc ",
        address: 28,
        c: "best seller",
        l: "like",
        id : 1,
        Click : 0,
    },    
]