
export const datasach = [
    {
        name: " Những Tù Nhân  của địa lý ",
        address: 1,
        c: "best seller",
        id: 1,
        Click : 0,
        author: "Tim Marshall",
        pulish: "30-11-2020",
        tran: "Phan Linh Lan",
        nxb : "Hội nhà văn",
        Topicid : 4,
        page: 432
    },
    {
        name: " Mùi Hương ",
        address: 2,
        l: "like",
        c: "best seller",
        id: 2 ,
        Click : 0,
        Topicid : 2,
        author : "Patrick Süskind",
        page: 347,
        pulish: "04-10-2019",
        tran: "Lê Chu Cầu",
        nxb : "Văn học" 
    },
    {
        name: " Sức mạnh của người mẹ nhật ",
        address: 3,
        c: "best seller",
        id: 3 ,
        Click : 0,
        Topicid : 7,
        author : "An Minjung",
        page: 276,
        pulish: "25-06-2018",
        tran: " Kim Ngân",
        nxb : "Văn học"
    },
    {
        name: " Phía tây không có gì lạ ",
        address: 4,
        id: 4 ,
        Click : 0,
        Topicid : 2,
        author : "Erich Maria Remarque",
        page: 248,
        pulish: "2017",
        tran: " Vũ Hương Giang",
        nxb : "Văn học"
    },
    {
        name: " Nhà Giả Kim ",
        address: 5,
        c: "best seller",
        id: 5,
        Click : 5,
        Topicid : 7,
        author : "Paulo Coelho",
        page: 220,
        pulish: "2020",
        tran: " Vũ Hương Giang",
        nxb : "Hội Nhà Văn"
    }, 
       {
        name: " Cha giàu cha nghèo ",
        address: 6,
        c: "best seller",
        Click : 6,
        id : 6,
        Topicid : 5,
        author : "	Robert T. Kiyosaki",
        page: 269,
        pulish: "11/12/2012",
        nxb : "Plata Publishing"
    },
    {
        name: " Onepiece ",
        address: 7,
        c: "best seller",
        Click : 0 ,
        id : 7,
        Topicid : 6,
        author : "Eiichiro Oda",
        page: 200,
        pulish: "1997-NOW",
        nxb : "Kim Dong"
    },
    {
        name: " Bí Kí Kinh Doanh Của Người Do Thái  ",
        address: 8,
        Click : 0,
        id : 8,
        Topicid : 3,
        author : "Minh Tân",
        page: 400,
        pulish: "2021",
        tran: "Minh Tân",
        nxb : "Hồng Đức"
    },
     {
        name: " Gió thổi mùa trăng năm ấy ",
        address:9,
        id : 9,
        Click : 0 ,
        Topicid : 2,
        author : "Vạn Lý Độc Hành",
        page: 288,
        pulish: "2022",
        tran: "Vạn Lý Độc Hành",
        nxb : "Hội Nhà Văn"
    }, 
    {
        name: " Đọc Vị Bất Kỳ Ai ",
        address:10,
        l: "like",
        id : 10,
        Click : 0,
        Topicid : 7,
        author : "David J Lieberman",
        page: 223,
        pulish: "2019",
        tran: "Đại Học Kinh Tế Quốc Dân",
        nxb : "Lao Động"
    }, 
    {
        name: " Khéo Ăn khéo Nói Sẽ Có Được Thiên Hạ ",
        address: 11,
        l: "like",
        Click : 0,
        id : 11,
        Topicid : 7,
        author : "Trác Nhã",
        page: 403,
        pulish: "2022",
        tran: "Nguyễn Phương Thảo",
        nxb : "Đại Học Sư Phạm"
    }, 
    {
        name: " Nghệ Thuật Từ Chối ",
        address: 12,
        id : 12,
        Click : 0,
        Topicid : 7,
        author : "Damon Zahariades",
        page: 160,
        pulish: "2020",
        tran: "	Ngô Tâm",
        nxb : "Hồng Đức"
    },
    {
        name: " 21 Bài học cho thế kỷ 21 ",
        address: 13,
        id : 13,
        Click : 0,
        m: "moi",
        Topicid : 7,
        author : "Yuval Noah Harari",
        page: 224,
        pulish: "02-10-2019",
        tran: "Dương Ngọc Trà",
        nxb : "Thế Giới"
    },    
    {
        name: " Lược Sử Tôn Giáo ",
        address:14,
        id : 14,
        Click : 0,
        m: "moi",
        Topicid : 5,
        author : " RICHARD HOLLOWAY",
        page: 308,
        pulish: "12-09-2019",
        tran: " Loan Vũ",
        nxb : "Thế Giới"
    },    
    {
        name: " Toán Học Một Chương Tiểu Thuyết ",
        address: 15,
        c: "best seller",
        id : 15,
        Click : 0,
        Topicid : 5,
        author : "Mickaël Launay",
        page: 332,
        pulish: "16-05-2019",
        tran: " Nhã phong",
        nxb : "Thế Giới"
    },  
    {
        name: " Lịch Sử Chiến Tranh",
        address: 16,
        id : 16,
        Click : 0,
        Topicid : 5,
        author : "John Keegan",
        page: 620,
        pulish: "19-11-2018",
        tran: "Thiếu Khanh",
        nxb : "Lao động"
    },
    {
        name: " Phía Sau Cuộc Chiến  ",
        address: 17,
        c: "best seller",
        l: "like",
        id : 17,
        Click : 0,
        Topicid : 4,
        author : "Deborah Nelson",
        page: 340,
        pulish: "12-05-2010",
        tran: "Deborah Nelson",
        nxb : "Thông Tấn"
    },
    {
        name: " Truyền Kì Mạn Lục ",
        address: 18,
        l: "like",
        id : 17,
        Click : 0,
        Topicid : 1,
        author : " Nguyễn Dữ",
        page: 254,
        pulish: "20-12-2018",
        tran: "Trúc Khê",
        nxb : "Hội nhà văn"
    }, 
        {
        name: " Tắt Đèn ",
        address: 19,
        id : 19,
        Click : 0,
        Topicid : 1,
        author : "Ngô Tất Tố",
        page: 231,
        pulish: "30-07-2018",
        nxb : "Hội nhà văn"
    }, 
    {
        name: " Nhật Kí Đặng Thùy Trâm ",
        address: 20,
        id : 20,
        Click : 0,
        Topicid : 1,
        author : "Đặng Thùy Trâm",
        page: 296,
        pulish: "24-06-2022",
        nxb : "Hội nhà văn"
    }, 
    {
        name: " Lặng Yên Cho Nước Chảy",
        address:21,
        id : 21,
        Click : 0,
        Topicid : 1,
        author : " Mai Văn Phấn",
        page: 120,
        pulish: "13-03-2018",
        nxb : "Hội nhà văn"
    }, 
    {
        name: " Ngoại ô ",
        address: 22,
        id : 22,
        Click : 0,
        Topicid : 1,
        author : " Nguyễn Đình Lập",
        page: 234,
        pulish: "23-08-2017",
        nxb : "Hội nhà văn"
    }, 
    {
        name: " Chúc Mẹ ngủ Ngon ",
        address: 23,
        id : 23,
        Click : 0,
        m: "moi",
        Topicid : 2,
        author : "Mi-ae Seo",
        page: 396,
        pulish: "10-11-2020",
        tran: "Nguyễn Thị Hồng Hà",
        nxb : "Hà Nội"
    }, 
    {
        name: " Donquixote ",
        address: 24,
        c: "best seller",
        l: "like",
        id : 24,
        Click : 0,
        m: "moi",
        Topicid : 2 ,
        author : "Jonathan Bousmar",
        page: 160,
        pulish: "14-05-2018",
        tran: " Phong Thu",
        nxb : "Văn học"
    },
    {
        name: " Bản Chất Của Người ",
        address: 25,
        l: "like",
        id : 25,
        Click : 0,
        Topicid : 7,
        author : "Han Kang",
        page: 350,
        pulish: "30-08-2019",
        tran: "Kim Ngân",
        nxb : "Hà Nội" 
    },  
    {
        name: " Những Kẻ Bày Mưu ",
        address: 26,
        c: "best seller",
        l: "like",
        id : 26,
        Click : 0,
        Topicid : 2,
        author : "Kim Un Su",
        page: 444,
        pulish: "27-09-2019",
        tran: "Thanh Phương",
        nxb : "Hà Nội" 
    },
    {
        name: " Tiệm Bánh Ngọt Lúc Nửa Đêm ",
        address: 27,
        c: "best seller",
        l: "like",
        id : 27,
        Click : 0,
        m:"moi",
        Topicid : 2,
        author : "Hoàng Mặc Kỳ",
        page: 540,
        pulish: "20-09-2019",
        tran: "Mai Dung",
        nxb : "Hà Nội" 
    },
    {
        name: " Hoa Hồng Sa Mạc ",
        address: 28,
        c: "best seller",
        l: "like",
        id : 28,
        Click : 0,
        Topicid : 2,
        author : "Luis Sepúlveda",
        page: 204,
        pulish: "22-08-2019",
        tran: "Lâm An",
        nxb : "Hội nhà văn" 
    },    
]
